# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3758ef3a18ec089ad65b4faa7a529d68afa1d13c0fe669c01c13e83723bed3ce64d7c8f74e3b0e4eaa65758bb23a408e72c683b31282b94a62db1ec8a77ba0dd

test:
  secret_key_base: 503d39e6b6e5aae25dacf4238c153dcc52c8f155b9bda27bba5b2941e47f7c3b793e2986d55427e85fa2ff0512f3072489d61ea7951a729ed9a1b7a65af63855

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
